version: '3'

services:
  db:
    container_name: singular-test-postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: singular-test
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: singular-test-nestjs
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src